Fix: Throw error if invalid model specified (+ refactor)
imperialCHEPI/healthgps pull request #160
Opened 2023-07-14 15:31 UTC by alexdewar

I've been playing around with `clang-tidy` as part of my work on #89 and it flagged a problem in `model_parser.cpp`. The issue is that if the JSON file contains an invalid model name, although an error message is printed, the code doesn't abort and will happily register a `nullptr` model definition in the cache.

I think part of the problem is that the `register_risk_factor_model_definitions` is rather long and with a lot of different branches in it, so it's easy to lose track of what the code is doing. I've split up the model loading into a series of separate functions with appropriate error handling in each.

2023-07-14 17:36 UTC, dalonsoa approved these changes
Looks good to me! Even if, for some reason, this does not solve all the problem, splitting long functions with a lot of nested branches is always a good idea.

2023-07-17 09:40 UTC, jamesturner246 requested changes
Yeah, that looks much nicer. Just a couple of trivial header fixups and it's good to go!

2023-07-17 09:40 UTC, jamesturner246 commented on src/HealthGPS.Console/model_parser.h
>  load_static_risk_model_definition(const poco::json &opt);
```suggestion
load_static_risk_model_definition(const std::string &model_name, const poco::json &opt);
```

2023-07-17 09:40 UTC, jamesturner246 commented on src/HealthGPS.Console/model_parser.h
>  load_dynamic_risk_model_definition(const poco::json &opt);
```suggestion
load_dynamic_risk_model_definition(const std::string &model_name, const poco::json &opt,
                                   const poco::SettingsInfo &settings);
```

2023-07-17 09:40 UTC, jamesturner246 commented on src/HealthGPS.Console/model_parser.h
> +/// @return The parsed JSON
```suggestion
/// @return The parsed JSON
/// @throw std::invalid_argument if file is missing
```

2023-07-17 09:40 UTC, jamesturner246 commented on src/HealthGPS.Console/model_parser.h
>  /// @return An instance of the hgps::HierarchicalLinearModelDefinition type
```suggestion
/// @return An instance of the hgps::HierarchicalLinearModelDefinition type
/// @throw std::invalid_argument if static model is unrecognised
```

2023-07-17 09:40 UTC, jamesturner246 commented on src/HealthGPS.Console/model_parser.h
>  /// @return An instance of the hgps::LiteHierarchicalModelDefinition type
```suggestion
/// @return An instance of the hgps::RiskFactorModelDefinition type
/// @throw std::invalid_argument if dynamic model is unrecognised
```

2023-07-17 17:39 UTC, alexdewar commented on src/HealthGPS.Console/model_parser.h
>  load_static_risk_model_definition(const poco::json &opt);
Oops! Good spot

2023-07-17 17:40 UTC, alexdewar commented on src/HealthGPS.Console/model_parser.h
>  load_static_risk_model_definition(const poco::json &opt);
Oops! Good spot

2023-07-17 18:11 UTC, jamesturner246 approved these changes
Looks good. Fire away!

2023-07-18 07:07 UTC, merged