Risk factor refactor
imperialCHEPI/healthgps pull request #195
Opened 2023-08-02 17:30 UTC by jamesturner246

Fixes #166 
(not really)

This has been somewhat of a lacklustre attempt that fell short of my ambition... All that was really achieved is the removal of duplicate risk factor listings from `France.EBHLM.json`, and changing a couple of data manager methods to fail on missing data, rather than warn and continue. As such, it should be quite quick to review. The main issue still seems to be the presence of code for handling Hierarchical static and dynamic models in the wider codebase, which is resisting refactor efforts.

In a moment of catharsis, I've now convinced myself that the best solution going forward is to merge static and dynamic RF model into a single model, which encapsulates all this extra HLM-specific code within it. 

See #194. I'd appreciate your input, as I'm itching to get started merging them, rather than doing more piecemeal refactors that aren't solving the underlying problem.

2023-08-02 20:03 UTC, israel-vieira approved these changes

2023-08-02 20:03 UTC, israel-vieira commented on src/HealthGPS.Console/configuration.cpp
The list of diseases can be long, 30+. The current validation will list all the invalid diseases key, if any, before exiting. The exception alternative will break at the first invalid key, the use will need to keep on trying until all are correct, in the end, both methods are accomplishing the required validation,  it is just a matter of style.

Mapping the config with the back-end in a case-sensitive world is never user friend, the identifier type tries to minimize the pain by making all keys lowercase.

2023-08-02 22:33 UTC, jamesturner246 commented on example/France.EBHLM.json
Agreed, the respective healthgps-tools script should also be updated. I'm considering a Python rewrite of the scripts, to sidestep the Windows R binding dependency.

2023-08-02 22:45 UTC, jamesturner246 commented on src/HealthGPS.Console/configuration.cpp
Case-sensitivity: fair point. In which case, the task then becomes removing the parts of the codebase that *are* case-sensitive. I've spotted a few.

Diseases: agree, a style choice. My concern in these cases has always been that by warning and continuing for dodgy input, that it makes the problem slightly less obvious to diagnose when it fails later on in the program, than if it were to immediately fail on loading. Perhaps this can be replaced with a function which reads all diseases, detects missing ones with printed debug info, before throwing an exception for *any* missing inputs, as opposed to a case-by-case exception.

2023-08-03 06:13 UTC, dalonsoa commented on src/HealthGPS.Console/configuration.cpp
I'm with @israel-vieira on this - collecting all that is invalid and providing a full list to the user (within meaningful indication of what is wrong) results on a better user experience than having to try again and again until all issues are sorted. We have another project where this is the approach and is indeed much better. 

All in all, having a strong validation and input pre-processing steps where things can fail early and inconsistencies fixed (casing, proxis, etc.) is a good thing that will result in simpler, easier to understand (and diagnose) code.

2023-08-03 07:26 UTC, israel-vieira commented on src/HealthGPS.Console/configuration.cpp
Personally, I don't consider users input validation as an exceptional circumstance, the validation should focus on helping the users to fix the wrong or missing information provided, perhaps the system should show valid options before exiting gracefully.

In general, users don't read or understand stack traces with a message hidden inside a large block of text, this is kind of information is more relevant for developers.

2023-08-03 13:04 UTC, alexdewar requested changes
I think this is the right approach on the whole. I've made some minor suggestions.

I agree with @dalonsoa and @israel-vieira that we do probably want to do "lazy failure" when loading the config and print errors as we go along, rather than aborting as soon as an error is found. I think what you've done is an improvement though, so I'd be inclined to merge this as is for now and worry about that later. As I was planning on tackling this myself (see #161), I'm happy for you to leave this task for me, if you like.

2023-08-03 17:28 UTC, jamesturner246 commented on src/HealthGPS.Tests/Datastore.Test.cpp
> +    hgps::core::Country uk = manager.get_country("GB");
Same.

2023-08-03 17:34 UTC, jamesturner246 commented on src/HealthGPS.Tests/Datastore.Test.cpp
>      }
Good spot.

2023-08-03 18:03 UTC, jamesturner246 commented on src/HealthGPS.Console/configuration.cpp
Agree with this ^. The user gets helpful human readable messages noting which keys were missing, and execution stops before there's a chance of accidental continuation on default values. I'm happy to merge, and happy to leave it with you if you already have the idea in mind.

2023-08-04 10:03 UTC, dalonsoa approved these changes
To be honest, nothing to add that @alexdewar has not explained much, much better - and with examples.

2023-08-07 11:07 UTC, merged