Add custom HgpsException, which contains a source_location instance.
imperialCHEPI/healthgps pull request #201
Opened 2023-08-13 20:32 UTC by jamesturner246

Fixes #193

2023-08-15 05:57 UTC, dalonsoa approved these changes
It looks good to me! I'm always confused about these things: being a compiled language, how is it possible to get the code location information? Is that contained in the binary somehow?

2023-08-15 08:45 UTC, jamesturner246 commented
Hummm, that is a good question...

The magic location finding stuff happens in `::current`, and I see there's a note in the [ref](https://en.cppreference.com/w/cpp/utility/source_location/current): 

> std::source_location::current typically requires compiler's built-in implementation. 

so maybe it gets it from the compiler's internal representation directly? not sure.

2023-08-15 10:49 UTC, alexdewar commented
I think it probably does require some compiler magic. Debug info can be stripped from binaries later, so that wouldn't be super robust.

Actually, you can see what it's doing here: https://godbolt.org/z/hxh7z41a6

You basically end up with a bunch of hard-coded constants saved into the binary representing the line number etc.

2023-08-15 11:05 UTC, alexdewar requested changes
I think this is a great usability improvement. Good work!

One small tweak you could make to the `HgpsException` is to forward on any extra arguments to `fmt::format`. Currently we've got things like this in a few places:

```cpp
throw hgps::core::HgpsException{fmt::format("Failed to parse adjustment file: {} or {}. {}",
                                            male_filename, female_filename, ex.what())};
```

And it would be nicer if you could just write:

```cpp
throw hgps::core::HgpsException{"Failed to parse adjustment file: {} or {}. {}", male_filename, female_filename, ex.what()};
```

You'll need to perfect-forward the arguments, using `std::forward`: https://en.cppreference.com/w/cpp/utility/forward

2023-08-15 20:40 UTC, jamesturner246 commented on src/HealthGPS.Core/exception.h
> +#endif // defined(__clang__) && __clang_major__ <= 14
Fine with me!

2023-08-15 21:14 UTC, israel-vieira approved these changes
Looks good!

2023-08-16 08:39 UTC, alexdewar commented on src/HealthGPS.Core/exception.h
> +#endif // defined(__clang__) && __clang_major__ <= 14
Come to think of it, if this is the only hackery needed to make things work on the
default clang version on Ubuntu 22.04, then maybe we don't need to rush to use a newer clang...

2023-08-16 08:43 UTC, jamesturner246 commented on src/HealthGPS.Core/exception.h
> +#endif // defined(__clang__) && __clang_major__ <= 14
That's what I had in mind, yeah.

2023-08-16 09:02 UTC, alexdewar commented on src/HealthGPS.Core/exception.cpp
> +    what_arg_ = fmt::format("{}:{}: {}", file_name(), line(), std::runtime_error::what());
I've only just noticed this, but how come you're passing `what_arg` to the parent constructor and then constructing a separate formatted string to give the extra source location info? Why doesn't the formatted string include `what_arg`? Surely we want this message to be visible to users. Why don't you construct a formatted string containing `what_arg` and the source location info, pass it to `std::runtime_error`'s constructor and drop the custom `what()` method?

2023-08-16 09:59 UTC, alexdewar approved these changes
LGTM!

2023-08-21 11:21 UTC, merged