Make properties required for JSON schema
imperialCHEPI/healthgps pull request #404
Opened 2024-05-30 15:25 UTC by alexdewar

For `file_info.json` I made only the `path` property required, because we don't actually use the others anywhere in the code (though they may be useful metadata).

I used the following script to make all properties for `data_index.json` required:

```py
import json
import sys

def add_required(d: dict):
    required = []
    for key, value in d.items():
        if isinstance(value, dict):
            add_required(value)
        if isinstance(value, list):
            for v in value:
                if isinstance(v, dict):
                    add_required(v)
        if key == "properties":
            required = list(k for k in d['properties'].keys() if k != "$schema")
    
    if required:
        d['required'] = required
        # d['additionalProperties'] = False

def process_file(path):
    with open(path) as f:
        d = json.load(f)
    
    add_required(d)

    with open(path, 'w') as f:
        json.dump(d, f)

if __name__ == '__main__':
    for path in sys.argv[1:]:
        process_file(path)
```

Making `additionalProperties` `false` seemed to break validation for some reason, so I've omitted it for now because it's less important.

Closes #403.

2024-06-04 12:32 UTC, jamesturner246 requested changes
Presumably you want `"maxItems": 2,` for the range pairs as well? Also a few of the dicts still don't have `required`, e.g. `prefixItems`.

Also what does `additionalProperties=false` do?

2024-06-04 15:27 UTC, jamesturner246 commented
Okay. But still `maxItems` for pairs though? Or no?

2024-06-04 15:40 UTC, alexdewar commented
Sorry, I misread that! I thought you said `minItems`... I'll fix that

2024-06-05 07:50 UTC, alexdewar commented
I've just looked at this and it does actually work as is, i.e. if you supply 3 values instead of 2 you get an error. The reason is that the `prefixItems` array enforces that you can't have more than two items (as well as making sure they're both integers).

It seems JSON schemas are not that intuitive :stuck_out_tongue:

2024-06-06 09:31 UTC, jamesturner246 approved these changes
LGTM!

2024-06-06 10:05 UTC, merged